# Generated by Django 2.2.3 on 2019-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="User code"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_text",
            field=models.TextField(blank=True, verbose_name="User text"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Common user"), (2, "Rare")],
                default=1,
                verbose_name="User type",
            ),
        ),
    ]
